- hosts: all
  become: yes
  become_method: sudo
  tasks:
          - name: echo tasks
            command: echo "{{ item }}"
            with_items:
             - foo
             - bar
             - baz

