print(type(3))
print(type(3.1))
a = 3
print(type(a))
print(type(a) is int)
print(type(a) is float)
print(isinstance(a, int))
print(pow(2, 10))
print(pow(16, 0.5))
print(pow(9, 22, 23))
print(divmod(13, 5))
print(round(2.3))
print(round(2.6))
print(round(2.672, 2))
print(round(2.679, 2))
print(round(1.5))
print(round(2.5))
print(round(2.675, 2))
print(2.3)
print(1, 2, 3, 4.5, 6.78)
print('abc')
name = input('お名前は？')
print(name)
print(len(name))
name_iter = iter(name)
print(next(name_iter))
print(next(name_iter))
print(next(name_iter))
print(next(name_iter))
# print(next(name_iter))
print(list(range(3)))
print(list(range(1, 10)))
print(list(range(2, 11, 2)))
print(list(range(9, 0, -2)))
print(bin(7))
print(hex(15))