- hosts: all
  vars:
          users:
                  kawasaki:
                          deirectory: /home/kawasaki
                          shell: /bin/bash
                          groups: ansible
                  kawabata:
                          directory: /home/tanaka
                          shell: /bin/zsh
                          groups: ansible

  become: yes
  become_method: sudo
  tasks:
  - name: user add
    user: name={{ item.key }} shell={{ item.value.shell }} groups={{ item.value.groups }} 
    with_dict: "{{ users }}"


